#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/../.." && pwd)"
root="$repo_root/m1/profile-overlay/airootfs"
entry="$root/usr/lib/clawos/clawos-entry"
onboard="$root/usr/lib/clawos/clawos-onboard"
onboard_ui="$root/usr/lib/clawos/clawos-onboard-ui"
onboard_server="$root/usr/lib/clawos/clawos-onboard-server"
return_to_setup="$root/usr/lib/clawos/clawos-return-to-setup"
lock="$root/usr/lib/clawos/clawos-lock"
power_menu="$root/usr/lib/clawos/clawos-power-menu"
system_menu="$root/usr/lib/clawos/clawos-system-menu"
power_action="$root/usr/lib/clawos/clawos-power-action"
browser="$root/usr/lib/clawos/clawos-browser"
node_install="$root/usr/lib/clawos/clawos-install-node"
node_enroll="$root/usr/lib/clawos/clawos-enroll-local-node"
gateway_watchdog="$root/usr/lib/clawos/clawos-gateway-watchdog"
activity_status="$root/usr/lib/clawos/clawos-activity-status"
activity_action="$root/usr/lib/clawos/clawos-activity-action"
attention_status="$root/usr/lib/clawos/clawos-attention-status"
surface="$root/usr/lib/clawos/clawos-surface"
surfaced="$root/usr/lib/clawos/clawos-surfaced"
appctl="$root/usr/lib/clawos/clawos-appctl"
app_registry="$root/usr/lib/clawos/app-registry.cjs"
app_palette="$root/usr/lib/clawos/clawos-app-palette"
intent_palette="$root/usr/lib/clawos/clawos-intent-palette"
app_from_fuzzel="$root/usr/lib/clawos/clawos-app-from-fuzzel"
webapp="$root/usr/lib/clawos/clawos-webapp"
actions_menu="$root/usr/lib/clawos/clawos-actions-menu"
agent_panel="$root/usr/lib/clawos/clawos-agent-panel"
agent_panel_status="$root/usr/lib/clawos/clawos-agent-panel-status"
agent_submit="$root/usr/lib/clawos/clawos-agent-submit"
agent_run="$root/usr/lib/clawos/clawos-agent-run"
agent_request="$root/usr/lib/clawos/clawos-agent-request"
agent_recover="$root/usr/lib/clawos/clawos-agent-recover"
screen_reader="$root/usr/lib/clawos/clawos-screen-reader-toggle"
installer="$root/usr/local/bin/clawos-install-dev"
live_welcome="$root/usr/lib/clawos/clawos-live-welcome"

bash -n "$entry" "$onboard" "$onboard_ui" "$browser" "$node_install" "$node_enroll" "$gateway_watchdog" \
  "$return_to_setup" "$lock" "$power_menu" "$power_action" "$activity_status" "$agent_recover" \
  "$activity_action" "$attention_status" "$surface" "$intent_palette" "$app_palette" "$app_from_fuzzel" "$webapp" \
  "$actions_menu" "$agent_panel" "$agent_panel_status" "$screen_reader" "$installer"
python3 -c 'import ast, pathlib, sys; ast.parse(pathlib.Path(sys.argv[1]).read_text())' "$live_welcome"
python3 -c 'import ast, pathlib, sys; [ast.parse(pathlib.Path(path).read_text()) for path in sys.argv[1:]]' \
  "$agent_submit" "$agent_run" "$agent_request" "$system_menu"
node --check "$surfaced"
node --check "$appctl"
node --check "$app_registry"
node --check "$onboard_server"
node --test "$repo_root/m1/tests/surfaced-persistence.test.mjs"
node --test "$repo_root/m1/tests/app-registry.test.mjs"
"$repo_root/m1/tests/local-node-enrollment.sh"
"$repo_root/m1/tests/gateway-watchdog.sh"
"$repo_root/m1/tests/attention-status.sh"
"$repo_root/m1/tests/agent-queue.py"
jq -e '.contracts.tools | index("clawos_app")' "$repo_root/m2/openclaw-plugin/openclaw.plugin.json" >/dev/null
jq -e '.contracts.tools | index("clawos_system")' "$repo_root/m2/openclaw-plugin/openclaw.plugin.json" >/dev/null
grep -Fq 'name: "clawos_app"' "$repo_root/m2/openclaw-plugin/index.js"
grep -Fq 'name: "clawos_system"' "$repo_root/m2/openclaw-plugin/index.js"
grep -Fq 'api.on("before_prompt_build"' "$repo_root/m2/openclaw-plugin/index.js"
grep -Fq 'api.on("before_tool_call"' "$repo_root/m2/openclaw-plugin/index.js"

grep -Fq 'openclaw onboard' "$onboard"
grep -Fq -- '--classic' "$onboard"
grep -Fq -- '--mode local' "$onboard"
grep -Fq -- '--mode remote' "$onboard"
grep -Fq -- '--gateway-auth token' "$onboard"
grep -Fq -- '--flow manual' "$onboard"
grep -Fq -- '--install-daemon' "$onboard"
grep -Fq -- '--skip-daemon' "$onboard"
grep -Fq -- '--skip-ui' "$onboard"
grep -Fq -- '--suppress-gateway-token-output' "$onboard"
grep -Fq 'nmtui-connect' "$onboard"
grep -Fq 'gateway.mode' "$entry"
grep -Fq 'clawos-onboard-ui' "$entry"
grep -Fq 'http://127.0.0.1:$port/api/health' "$onboard_ui"
grep -Fq 'pathname === "/api/health"' "$onboard_server"
if grep -Fq 'http://127.0.0.1:$port/api/status' "$onboard_ui"; then
  echo "Onboarding readiness must not call the slow status endpoint." >&2
  exit 1
fi
grep -Fq '127.0.0.1' "$onboard_server"
grep -Fq -- '--non-interactive' "$onboard_server"
grep -Fq -- '--accept-risk' "$onboard_server"
grep -Fq 'full-approvals' "$onboard_server"
# Choosing the level the broker already has must not raise a Polkit prompt.
grep -Fq 'if (status?.securityLevel === level) return { skipped: true, level };' "$onboard_server"
grep -Fq 'randomBytes(32)' "$onboard_server"
grep -Fq 'readOpenClawEnv("OPENCLAW_GATEWAY_TOKEN")' "$onboard_server"
grep -Fq 'if (!savedGatewayToken) await saveOpenClawEnv' "$onboard_server"
grep -Fq 'child.stdout.resume()' "$onboard_server"
grep -Fq 'const existingMode = await gatewayMode()' "$onboard_server"
grep -Fq 'if (existingMode !== mode)' "$onboard_server"
grep -Fq 'const checkpointPath = path.join(stateHome, "clawos", "onboarding.json")' "$onboard_server"
grep -Fq 'setupStages.indexOf(checkpoint.stage)' "$onboard_server"
grep -Fq 'checkpoint?.stage === "complete"' "$onboard_server"
grep -Fq 'checkpoint?.stage !== "complete"' "$onboard_server"
grep -Fq 'status.mode && status.setupComplete' "$root/usr/share/clawos/onboarding/app.js"
grep -Fq 'Setup was interrupted after ${status.stage}' "$root/usr/share/clawos/onboarding/app.js"
! grep -Fq 'saveOpenClawEnv("OLLAMA_API_KEY"' "$onboard_server"
grep -Fq 'configure --section model' "$root/usr/lib/clawos/clawos-provider-setup"
! grep -Fq 'Ollama Cloud' "$root/usr/share/clawos/onboarding/index.html"
! grep -Fq 'ollama-cloud' "$root/usr/share/clawos/onboarding/app.js"
grep -Fq '/api/provider-setup' "$onboard_server"
grep -Fq '"--force", "--accept-capabilities"' "$onboard_server"
grep -Fq '"clawos_surface", "clawos_activity", "clawos_app"' "$onboard_server"
grep -Fq '"clawos_surface", "clawos_activity", "clawos_app", "clawos_system"' "$onboard_server"
grep -Fq 'policyKey = "tools.alsoAllow"' "$onboard_server"
grep -Fq '"clawos-gmail": { cdpUrl: "http://127.0.0.1:9223"' "$onboard_server"
grep -Fq '"clawos-outlook": { cdpUrl: "http://127.0.0.1:9224"' "$onboard_server"
grep -Fq '"config", "set", "browser.enabled", "true", "--strict-json"' "$onboard_server"
grep -Fq '"config", "set", "plugins.entries.browser.enabled", "true", "--strict-json"' "$onboard_server"
grep -Fq '"config", "get", "tools.allow"' "$onboard_server"
grep -Fq '"config", "set", policyKey, JSON.stringify(merged), "--strict-json"' "$onboard_server"
grep -Fq '"plugins.entries.clawos-system.hooks.allowConversationAccess", "true", "--strict-json"' "$onboard_server"
grep -Fq '"plugins.entries.clawos-system.hooks.allowPromptInjection", "true", "--strict-json"' "$onboard_server"
grep -Fq 'saveOpenClawEnv("OPENCLAW_GATEWAY_TOKEN"' "$onboard_server"
grep -Fq '"--secret-input-mode", "ref"' "$onboard_server"
grep -Fq '"--gateway-token-ref-env"' "$onboard_server"
if grep -Fq '"--ollama-cloud-api-key"' "$onboard_server" ||
   grep -Fq '"--gateway-token",' "$onboard_server" ||
   grep -Fq '"--remote-token"' "$onboard_server"; then
  echo "Graphical onboarding must not place secrets in process arguments." >&2
  exit 1
fi
node --check "$root/usr/share/clawos/onboarding/app.js"
grep -Fq 'textContent' "$root/usr/share/clawos/onboarding/app.js"
grep -Fq 'Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>F3' "$root/usr/share/clawos/onboarding/index.html"
grep -Fq 'The local setup service stopped responding' "$root/usr/share/clawos/onboarding/app.js"
grep -Fq 'Enter Agent workspace' "$root/usr/share/clawos/onboarding/index.html"
! grep -Fq 'setup-header' "$root/usr/share/clawos/onboarding/index.html"
! grep -Fq 'setup-footer' "$root/usr/share/clawos/onboarding/index.html"
grep -Fq 'Setup required' "$root/usr/lib/clawos/clawos-panel-status"
grep -Fq 'gateway.remote.url' "$root/usr/lib/clawos/clawos-panel-status"
grep -Fq "json 'Controller offline'" "$root/usr/lib/clawos/clawos-panel-status"
grep -Fq 'Review approvals", ["/usr/lib/clawos/clawos-approval"]' "$root/usr/lib/clawos/clawos-agent-shelf"
grep -Fq 'clawos_attention.py' "$attention_status"
grep -Fq 'f"Review {count}"' "$root/usr/lib/clawos/clawos_attention.py"
grep -Fq 'Work and decisions' "$repo_root/m3/clawosd/clawos_approval.py"
grep -Fq 'tasks", "cancel"' "$repo_root/m3/clawosd/clawos_approval.py"
grep -Fq 'from clawos_attention import collect, acknowledge, actionable_failure' "$repo_root/m3/clawosd/clawos_approval.py"
grep -Fq 'approvals", "resolve"' "$repo_root/m3/clawosd/clawos_approval.py"
grep -Fq 'ClawOS Setup' "$return_to_setup"
grep -Fq 'gtklock' "$lock"
grep -Fq 'passwd --status' "$lock"
grep -Fq 'clawos-system-menu' "$power_menu"
grep -Fq 'panel.set_margin_top(6)' "$system_menu"
grep -Fq 'systemctl reboot' "$power_action"
grep -Fq 'systemctl poweroff' "$power_action"
grep -Fq 'swayidle -w timeout 900' "$root/etc/clawos/sway.conf"
grep -Fq 'clawos-power-menu' "$root/etc/clawos/waybar/config.jsonc"
grep -Fq 'custom/activity' "$root/etc/clawos/waybar/config.jsonc"
grep -Fq 'clawos-activity-status' "$root/etc/clawos/waybar/config.jsonc"
grep -Fq 'clawos-attention-status' "$root/etc/clawos/waybar/config.jsonc"
grep -Fq 'clawos-intent-palette' "$root/etc/clawos/waybar/config.jsonc"
grep -Fq 'clawos-activity-action' "$root/etc/clawos/waybar/config.jsonc"
! grep -Fq '"on-click": "/usr/lib/clawos/clawos-app-palette"' "$root/etc/clawos/waybar/config.jsonc"
grep -Fq 'Mod1+space exec /usr/lib/clawos/clawos-actions-menu' "$root/etc/clawos/sway.conf"
grep -Fq 'Mod1+Shift+space exec /usr/lib/clawos/clawos-intent-palette' "$root/etc/clawos/sway.conf"
grep -Fq 'Mod1+Escape exec /usr/lib/clawos/clawos-activity-action' "$root/etc/clawos/sway.conf"
grep -Fq 'exec --no-startup-id /usr/lib/clawos/clawos-agent-shelf' "$root/etc/clawos/sway.conf"
grep -Fq 'exec --no-startup-id /usr/lib/clawos/clawos-agent-recover' "$root/etc/clawos/sway.conf"
grep -Fq '["/usr/lib/clawos/clawos-agent-submit"]' "$root/usr/lib/clawos/clawos-agent-shelf"
grep -Fq 'agent:main:main' "$agent_run"
grep -Fq '"--message-file"' "$agent_run"
! grep -Fq '"--message", prompt' "$root/usr/lib/clawos/clawos-agent-shelf"
grep -Fq 'StandardOutput=null' "$agent_submit"
grep -Fq 'O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600' "$agent_submit"
grep -Fq '"Resume request"' "$repo_root/m3/clawosd/clawos_approval.py"
grep -Fq 'may repeat external or machine effects' "$repo_root/m3/clawosd/clawos_approval.py"
grep -Fq 'clawos-agent-request list' "$agent_recover"
grep -Fq 'Ask Agent about' "$root/usr/lib/clawos/clawos-agent-shelf"
grep -Fq 'surface not in {"Agent", "Setup", "Machine", "Terminal", "Build"}' "$root/usr/lib/clawos/clawos-agent-shelf"
grep -Fq 'projected_status()' "$root/usr/lib/clawos/clawos-agent-shelf"
grep -Fq 'threading.Thread(target=self.queue_agent' "$root/usr/lib/clawos/clawos-agent-shelf"
grep -Fq 'placeholder=What do you want to do?' "$root/etc/clawos/intent-fuzzel.ini"
grep -Fq 'More applications' "$intent_palette"
grep -Fq 'clawos-app-palette' "$intent_palette"
grep -Fq "state_label='Ready'" "$activity_status"
grep -Fq 'click to return to' "$activity_status"
grep -Fq 'clawos-appctl agent' "$activity_action"
grep -Fq 'exec /usr/lib/clawos/clawos-surface agent' "$activity_action"
grep -Fq 'resize set width $width px height $height px, move position 0 0' "$surface"
grep -Fq 'launch-prefix=/usr/lib/clawos/clawos-app-from-fuzzel' "$root/etc/clawos/fuzzel.ini"
grep -Fq 'case "app.list"' "$surfaced"
grep -Fq 'case "app.open"' "$surfaced"
grep -Fq 'resolveApplication' "$surfaced"
grep -Fq '["con", "floating_con"].includes(node.type)' "$surfaced"
grep -Fq 'allowHalfOpen: true' "$surfaced"
grep -Fq 'floating_maximum_size -1 x -1' "$root/etc/clawos/sway.conf"
grep -Fq 'spawn("/usr/bin/gio", ["launch", application.filePath]' "$app_registry"
grep -Fq 'X-ClawOS-AppId=web:gmail' "$root/usr/share/applications/clawos-gmail.desktop"
grep -Fq 'X-ClawOS-AppId=web:outlook' "$root/usr/share/applications/clawos-outlook.desktop"
grep -Fq 'X-ClawOS-BrowserProfile=clawos-gmail' "$root/usr/share/applications/clawos-gmail.desktop"
grep -Fq 'X-ClawOS-BrowserProfile=clawos-outlook' "$root/usr/share/applications/clawos-outlook.desktop"
grep -Fq -- '--remote-debugging-port="$cdp_port"' "$webapp"
if grep -Eq 'custom/(agent|actions)' "$root/etc/clawos/waybar/config.jsonc"; then
  echo "Agent and Actions must not be duplicated in the top bar." >&2
  exit 1
fi
grep -Fq 'clawos-agent-panel' "$root/usr/lib/clawos/clawos-agent-shelf"
grep -Fq 'clawos-actions-menu' "$root/usr/lib/clawos/clawos-agent-shelf"
grep -Fq 'view-more-symbolic' "$root/usr/lib/clawos/clawos-agent-shelf"
! grep -Fq 'Gtk.Button(label="+")' "$root/usr/lib/clawos/clawos-agent-shelf"
grep -Fq 'fcntl.LOCK_EX | fcntl.LOCK_NB' "$repo_root/m3/clawosd/clawos_approval.py"
grep -Fq 'clawos-intent-palette' "$actions_menu"
grep -Fq '@define-color oc_accent_primary #f5654a;' "$root/etc/clawos/design-system.css"
grep -Fq '@import url("../design-system.css");' "$root/etc/clawos/waybar/style.css"
grep -Fq '@import url("design-system.css");' "$root/etc/clawos/agent-shelf.css"
grep -Fq 'NO_AT_BRIDGE=0' "$root/usr/lib/clawos/clawos-session"
test -x "$root/usr/lib/clawos/clawos-clock-status"
grep -Fq '"custom/clock"' "$root/etc/clawos/waybar/config.jsonc"
grep -Fq '"agentCapability": "google-mail"' "$root/usr/share/clawos/webapps/gmail.json"
grep -Fq '"agentCapability": "microsoft-mail"' "$root/usr/share/clawos/webapps/outlook.json"
if grep -Fq 'custom/add-surface' "$root/etc/clawos/waybar/config.jsonc"; then
  echo "The agent owns surface lifecycle; the panel must not advertise app launch buttons." >&2
  exit 1
fi
if grep -Fq 'sway/workspaces' "$root/etc/clawos/waybar/config.jsonc"; then
  echo "Fixed application workspaces are not the ClawOS navigation model." >&2
  exit 1
fi
grep -Fq '"on-click": "/usr/lib/clawos/clawos-power-menu"' "$root/etc/clawos/waybar/config.jsonc"
if grep -Fq 'custom/system' "$root/etc/clawos/waybar/config.jsonc"; then
  echo "The ClawOS wordmark owns the system menu; a second System module is not allowed." >&2
  exit 1
fi
grep -Fq 'Restarting ClawOS' "$root/usr/share/plymouth/themes/clawos/clawos.script"
grep -Fq 'passwd --root "$mount_root" --stdin clawos <"$key_file"' "$installer"
if grep -Fq 'getty@tty1.service.d/autologin.conf' "$installer"; then
  echo "The graphical ClawOS path must not fall through to a tty1 root autologin." >&2
  exit 1
fi
grep -Fq 'clawos-install-node' "$entry"
grep -Fq 'clawos-enroll-local-node' "$entry"
grep -Fq 'securityLevel // "full-root"' "$node_enroll"
grep -Fq 'node identity --json' "$node_enroll"
grep -Fq 'devices list --json' "$node_enroll"
grep -Fq 'nodes pending --json' "$node_enroll"
grep -Fq 'index("clawos.system")' "$node_enroll"
grep -Fq 'clawos-gateway-watchdog "$$"' "$browser"
grep -Fq 'failures >= 2' "$gateway_watchdog"
grep -Fq 'const lockPath = path.join(stateDir, "surfaced.lock")' "$surfaced"
grep -Fq 'liveOwner = command.includes("clawos-surfaced")' "$surfaced"
grep -Fq 'clawos-role"' "$onboard_server"
test -x "$root/usr/lib/clawos/clawos-role"
bash -n "$root/usr/lib/clawos/clawos-role"
test -x "$root/usr/lib/clawos/clawos-security-mode"
bash -n "$root/usr/lib/clawos/clawos-security-mode"
grep -Fq 'security.level.configure' "$onboard_server"
grep -Fq 'output Virtual-1 mode 1440x900 scale 1' "$root/etc/clawos/sway.conf"
grep -Fq 'gateway.remote.url' "$node_install"
grep -Fq 'ws://127.0.0.1:$port' "$node_install"
grep -Fq 'umask 077' "$browser"
grep -Fq 'file://$bootstrap' "$browser"
grep -Fq 'gateway_token gateway.auth.token' "$browser"
grep -Fq 'read_openclaw_env OPENCLAW_GATEWAY_TOKEN' "$browser"
if grep -Eq 'config get gateway\.(auth|remote)\.token' "$browser"; then
  echo "ClawOS browser must not use OpenClaw's redacted config output as a token." >&2
  exit 1
fi
grep -Fq 'cp -a /usr/lib/node_modules/openclaw' "$installer"
grep -Fq 'openclaw --version | grep -Fq "$OPENCLAW_VERSION"' "$installer"
! grep -Fq 'npm install --global' "$installer"
grep -Fq 'umask 022' "$installer"
grep -Fq 'runuser -u clawos -- openclaw --version' "$installer"
grep -Fq 'chromium foot fuzzel sway swaybg waybar' "$root/usr/lib/clawos/clawos-install-packages.sh"
grep -Fq '/usr/share/applications/clawos-gmail.desktop' "$installer"
grep -Fq 'clawos-app-from-fuzzel' "$installer"
grep -Fq 'Inspect system' "$live_welcome"
grep -Fq 'The full Agent workspace is created after installation.' "$live_welcome"
grep -Fq 'LUKS2 encryption  ·  Full Root (passwordless sudo)  ·  Recovery TTY on Ctrl+Alt+F3' "$live_welcome"
grep -Fq 'self.install_button.set_sensitive(False)' "$live_welcome"
grep -Fq 'Gdk.KEY_Escape' "$live_welcome"
grep -Fq 'self.screen_width' "$live_welcome"
grep -Fq 'Restart into ClawOS' "$live_welcome"

if grep -Eq -- '--(openai|anthropic|gemini|remote)-.*key' "$onboard"; then
  echo "ClawOS onboarding must not pass provider secrets on the command line." >&2
  exit 1
fi

if [[ -d "$root/usr/share/clawos-launch" ]]; then
  echo "Parallel ClawOS web shell detected." >&2
  exit 1
fi

echo "ClawOS onboarding static checks passed."
