# Derived from archiso v89 configs/releng/pacman.conf (pacman stock config, GPL-2.0-or-later, via archiso
# GPL-3.0-or-later); reduced and modified by ClawOS 2026-08-26. Not MIT. SPDX-License-Identifier: GPL-3.0-or-later
[options]
HoldPkg = pacman glibc
Architecture = auto
CheckSpace
ParallelDownloads = 5
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Required

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist
